### ISSUE TITLE
Custom Icons don’t load until edit button is pressed.

### ISSUE THREAD

**Issue by psychsatani** [phibr0/obsidian-advanced-toolbar#3] opened 2021-08-02 22:26 UTC
https://user-images.githubusercontent.com/78266798/127931431-8d4c54b7-f5ff-4a37-b957-a77b6544f75d.MOV

**Comment by phibr0** [comment] 2021-08-10 09:04
Could give a little more Context? Does this happen right after you started Obsidian?

**Comment by psychsatani** [comment] 2021-08-10 20:50
If by started you mean launched the app, then yes.

**Comment by phibr0** [comment] 2021-08-10 20:54
Okay then I think I cant do much about that. The Problem is I can only first inject the Icons when Obsidian is fully initialized, this also means the Toolbar is already open and the commands don't have icons yet.

**Comment by phibr0** [comment] 2021-08-10 20:55
What I could experiment with is closing and re-opening the toolbar once the Icons are first injected

**Comment by psychsatani** [comment] 2021-08-10 23:42
Whatever you can do to make this better is good. I will try to memorize what these question marks mean by their spatial position (I have put four rows). Each of these enable me to use quick add plugin to quickly capture something into the journal section of my daily not. I get out of the app immediately so that it doesn't feel like work to navigate to the right place and do careful structured typing of the many entries over the day. You have already made my work so much easier. Thank you!

**Comment by phibr0** [comment] 2021-08-11 21:40
Could you test if it works properly now?

**Comment by psychsatani** [comment] 2021-08-11 22:58
Still the same. After launching the app, i Gotta try to edit the document and that's when the icons show.

**Comment by phibr0** [comment] 2021-08-12 12:04
Wait, does the Toolbar show while you are in Preview Mode?

**Comment by psychsatani** [comment] 2021-08-12 12:21
I have kept "always show toolbar" on. So it shows in preview mode. But not upon launching obsidian. When obsidian launches with the note in preview mode, there is no toolbar at all. When it launches in edit mode, the toolbar loads (all 4 rows that I have set) but custom icons don't show.

**Comment by psychsatani** [comment] 2021-08-12 12:25
https://user-images.githubusercontent.com/78266798/129196167-3366058e-f5c1-49bc-abe1-220aadf14c61.MOV

**Comment by psychsatani** [comment] 2021-08-12 12:27
https://user-images.githubusercontent.com/78266798/129196513-236435f6-2da5-47c2-b28f-cd5f1a15ee97.MOV

**Comment by phibr0** [comment] 2021-08-12 12:35
Could you please try Version 1.6.1?

**Comment by psychsatani** [comment] 2021-08-12 12:56
Oh I am sorry I should have updated. I had updated on iPad but forgot to do that here and assumed the error persisted. Thanks it is working now. 🙏🏻

**Closed** 2021-08-12 16:13 UTC
